// Curated Unicode emoji set for the newsletter editor. Inserting the raw
// characters (rather than TipTap emoji nodes/images) keeps them as plain text:
// they pass untouched through DOMPurify and render natively in every email
// client. Keywords power the picker's search box.

export interface EmojiEntry {
  char: string;
  name: string;
  keywords: string;
}

export interface EmojiGroup {
  id: string;
  label: string;
  /** Emoji shown on the category tab. */
  icon: string;
  emojis: EmojiEntry[];
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "😊",
    emojis: [
      { char: "😀", name: "grinning", keywords: "smile happy face grin" },
      { char: "😃", name: "smiley", keywords: "smile happy joy" },
      { char: "😄", name: "grin", keywords: "smile happy joy laugh" },
      { char: "😁", name: "beaming", keywords: "smile happy grin" },
      { char: "😆", name: "laughing", keywords: "happy haha laugh lol" },
      { char: "😅", name: "sweat smile", keywords: "happy relief phew" },
      { char: "😂", name: "joy", keywords: "laugh cry haha lol tears" },
      { char: "🤣", name: "rolling laughing", keywords: "rofl lol laugh" },
      { char: "🙂", name: "slight smile", keywords: "smile happy" },
      { char: "🙃", name: "upside down", keywords: "silly sarcasm" },
      { char: "😉", name: "wink", keywords: "flirt playful" },
      { char: "😊", name: "blush", keywords: "smile happy warm shy" },
      { char: "😇", name: "innocent", keywords: "halo angel" },
      { char: "🥰", name: "smiling hearts", keywords: "love adore crush" },
      { char: "😍", name: "heart eyes", keywords: "love crush adore" },
      { char: "🤩", name: "star struck", keywords: "excited wow amazed" },
      { char: "😘", name: "blowing kiss", keywords: "love kiss flirt" },
      { char: "😋", name: "yum", keywords: "delicious tasty tongue" },
      { char: "😌", name: "relieved", keywords: "calm content peace" },
      { char: "😎", name: "sunglasses", keywords: "cool chill" },
      { char: "🥳", name: "partying", keywords: "party celebrate hooray" },
      { char: "🤗", name: "hugging", keywords: "hug warm care" },
      { char: "🤔", name: "thinking", keywords: "hmm consider ponder" },
      { char: "😴", name: "sleeping", keywords: "sleep tired rest zzz" },
      { char: "🥺", name: "pleading", keywords: "puppy eyes please" },
      { char: "😢", name: "crying", keywords: "sad tear" },
      {
        char: "🥲",
        name: "smiling tear",
        keywords: "grateful touched happy sad",
      },
      { char: "🤭", name: "hand over mouth", keywords: "oops giggle shy" },
      {
        char: "🥹",
        name: "holding tears",
        keywords: "grateful proud emotional",
      },
    ],
  },
  {
    id: "gestures",
    label: "Gestures",
    icon: "👋",
    emojis: [
      { char: "👋", name: "wave", keywords: "hi hello bye greeting" },
      { char: "🤚", name: "raised back hand", keywords: "hand stop" },
      { char: "🖐️", name: "hand fingers splayed", keywords: "hand five" },
      { char: "✋", name: "raised hand", keywords: "stop high five hand" },
      { char: "👌", name: "ok hand", keywords: "okay perfect nice" },
      {
        char: "🤌",
        name: "pinched fingers",
        keywords: "italian gesture chef kiss",
      },
      { char: "🤏", name: "pinch", keywords: "small little bit" },
      { char: "✌️", name: "peace", keywords: "victory two peace" },
      { char: "🤞", name: "fingers crossed", keywords: "luck hope wish" },
      { char: "🫰", name: "finger heart", keywords: "love money snap" },
      { char: "🤟", name: "love you", keywords: "ily love rock" },
      { char: "🤙", name: "call me", keywords: "hang loose shaka" },
      { char: "👈", name: "point left", keywords: "left direction" },
      { char: "👉", name: "point right", keywords: "right direction" },
      { char: "👆", name: "point up", keywords: "up above" },
      { char: "👇", name: "point down", keywords: "down below" },
      { char: "☝️", name: "index up", keywords: "one first point" },
      { char: "👍", name: "thumbs up", keywords: "yes like good approve" },
      { char: "👎", name: "thumbs down", keywords: "no dislike bad" },
      { char: "✊", name: "raised fist", keywords: "power solidarity" },
      { char: "👊", name: "fist bump", keywords: "punch bump" },
      { char: "👏", name: "clap", keywords: "applause bravo praise" },
      {
        char: "🙌",
        name: "raised hands",
        keywords: "celebrate praise hooray yay",
      },
      { char: "👐", name: "open hands", keywords: "hug open" },
      { char: "🤲", name: "palms up", keywords: "offer pray receive" },
      { char: "🤝", name: "handshake", keywords: "deal agree partner meet" },
      {
        char: "🙏",
        name: "namaste",
        keywords: "pray thanks please gratitude hope",
      },
      { char: "💪", name: "muscle", keywords: "strong flex strength power" },
      { char: "🫶", name: "heart hands", keywords: "love care thanks" },
    ],
  },
  {
    id: "wellness",
    label: "Wellness",
    icon: "🧘",
    emojis: [
      {
        char: "🧘‍♀️",
        name: "woman meditating",
        keywords: "yoga meditate calm lotus zen",
      },
      {
        char: "🧘‍♂️",
        name: "man meditating",
        keywords: "yoga meditate calm lotus zen",
      },
      {
        char: "🧘",
        name: "person meditating",
        keywords: "yoga meditate calm lotus zen",
      },
      {
        char: "🤸‍♀️",
        name: "woman cartwheel",
        keywords: "flexible gymnast stretch",
      },
      { char: "🤸", name: "cartwheel", keywords: "flexible gymnast stretch" },
      { char: "💆‍♀️", name: "woman massage", keywords: "relax spa self care" },
      { char: "💆", name: "massage", keywords: "relax spa self care" },
      { char: "🚶‍♀️", name: "walking", keywords: "walk stroll move" },
      { char: "🏃‍♀️", name: "running", keywords: "run exercise cardio" },
      { char: "🚴‍♀️", name: "cycling", keywords: "bike ride exercise" },
      { char: "🧗‍♀️", name: "climbing", keywords: "climb bouldering strength" },
      { char: "🏋️‍♀️", name: "lifting", keywords: "weights gym strength" },
      { char: "🏆", name: "trophy", keywords: "win award champion" },
      { char: "🥇", name: "gold medal", keywords: "first win award" },
      { char: "🎯", name: "target", keywords: "goal aim focus bullseye" },
      { char: "🕉️", name: "om", keywords: "yoga meditation hindu spirit" },
      { char: "☮️", name: "peace", keywords: "calm harmony" },
      { char: "🧿", name: "nazar", keywords: "protection evil eye" },
      { char: "🪬", name: "hamsa", keywords: "protection spirit" },
      { char: "💤", name: "zzz", keywords: "sleep rest tired" },
      { char: "🛀", name: "bath", keywords: "relax soak self care" },
      { char: "🫁", name: "lungs", keywords: "breath breathe pranayama" },
    ],
  },
  {
    id: "nature",
    label: "Nature",
    icon: "🌿",
    emojis: [
      {
        char: "🌸",
        name: "cherry blossom",
        keywords: "flower spring pink bloom",
      },
      { char: "🌷", name: "tulip", keywords: "flower spring" },
      { char: "🌹", name: "rose", keywords: "flower love red" },
      { char: "🌺", name: "hibiscus", keywords: "flower tropical" },
      { char: "🌻", name: "sunflower", keywords: "flower summer yellow" },
      { char: "🌼", name: "blossom", keywords: "flower daisy" },
      { char: "🪷", name: "lotus", keywords: "flower yoga zen calm" },
      { char: "💐", name: "bouquet", keywords: "flowers gift thanks" },
      { char: "🍀", name: "four leaf clover", keywords: "luck lucky" },
      { char: "🌿", name: "herb", keywords: "leaf plant green" },
      { char: "🍃", name: "leaves", keywords: "wind plant green nature" },
      { char: "🌱", name: "seedling", keywords: "grow sprout new plant" },
      { char: "🌳", name: "tree", keywords: "nature forest green" },
      { char: "🌴", name: "palm tree", keywords: "tropical beach vacation" },
      { char: "🍁", name: "maple leaf", keywords: "autumn fall" },
      { char: "🍂", name: "fallen leaves", keywords: "autumn fall" },
      { char: "🌾", name: "sheaf", keywords: "wheat grain harvest" },
      { char: "☀️", name: "sun", keywords: "sunny bright day warm" },
      { char: "🌞", name: "sun face", keywords: "sunny bright happy" },
      {
        char: "⛅",
        name: "sun behind cloud",
        keywords: "partly cloudy weather",
      },
      { char: "🌈", name: "rainbow", keywords: "colorful pride hope" },
      { char: "🌙", name: "crescent moon", keywords: "night moon evening" },
      { char: "⭐", name: "star", keywords: "favorite night" },
      { char: "🌟", name: "glowing star", keywords: "sparkle shine special" },
      {
        char: "✨",
        name: "sparkles",
        keywords: "shine magic special new clean",
      },
      { char: "💫", name: "dizzy", keywords: "star sparkle" },
      { char: "🔥", name: "fire", keywords: "hot lit flame energy" },
      { char: "🌊", name: "wave", keywords: "ocean water sea flow" },
      { char: "❄️", name: "snowflake", keywords: "cold winter snow" },
      { char: "🦋", name: "butterfly", keywords: "transform spring insect" },
      { char: "🐝", name: "bee", keywords: "honey buzz insect" },
      { char: "🕊️", name: "dove", keywords: "peace bird" },
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: "🍵",
    emojis: [
      { char: "☕", name: "coffee", keywords: "cafe hot drink morning" },
      { char: "🍵", name: "tea", keywords: "matcha green hot drink calm" },
      { char: "🧋", name: "bubble tea", keywords: "boba drink" },
      { char: "🥤", name: "cup straw", keywords: "drink soda smoothie" },
      { char: "💧", name: "droplet", keywords: "water hydrate" },
      { char: "🍎", name: "apple", keywords: "fruit healthy red" },
      { char: "🍓", name: "strawberry", keywords: "fruit berry" },
      { char: "🫐", name: "blueberries", keywords: "fruit berry" },
      { char: "🍇", name: "grapes", keywords: "fruit" },
      { char: "🍊", name: "orange", keywords: "fruit citrus" },
      { char: "🍋", name: "lemon", keywords: "fruit citrus sour" },
      { char: "🥑", name: "avocado", keywords: "healthy toast fruit" },
      { char: "🥗", name: "salad", keywords: "healthy greens bowl" },
      { char: "🥕", name: "carrot", keywords: "vegetable healthy" },
      { char: "🍞", name: "bread", keywords: "toast loaf" },
      { char: "🥐", name: "croissant", keywords: "breakfast pastry" },
      { char: "🍪", name: "cookie", keywords: "treat dessert sweet" },
      { char: "🍫", name: "chocolate", keywords: "treat dessert sweet" },
      { char: "🍯", name: "honey", keywords: "sweet natural" },
      { char: "🍰", name: "cake slice", keywords: "dessert birthday sweet" },
      { char: "🧁", name: "cupcake", keywords: "dessert sweet treat" },
      {
        char: "🎂",
        name: "birthday cake",
        keywords: "celebrate party dessert",
      },
      { char: "🍷", name: "wine", keywords: "drink celebrate" },
      { char: "🥂", name: "cheers", keywords: "toast celebrate champagne" },
    ],
  },
  {
    id: "places",
    label: "Places",
    icon: "🏡",
    emojis: [
      { char: "🏡", name: "home garden", keywords: "house home studio" },
      { char: "🏠", name: "house", keywords: "home studio" },
      { char: "🏢", name: "office", keywords: "building work" },
      { char: "⛰️", name: "mountain", keywords: "nature hike outdoors" },
      { char: "🏔️", name: "snowy mountain", keywords: "peak nature" },
      { char: "🏕️", name: "camping", keywords: "tent outdoors nature retreat" },
      { char: "🏖️", name: "beach", keywords: "vacation sand ocean" },
      { char: "🏝️", name: "island", keywords: "tropical vacation getaway" },
      { char: "🌅", name: "sunrise", keywords: "morning dawn beach" },
      { char: "🌄", name: "sunrise mountains", keywords: "morning dawn" },
      { char: "⛵", name: "sailboat", keywords: "sail water travel" },
      { char: "✈️", name: "airplane", keywords: "flight travel trip" },
      { char: "🧳", name: "luggage", keywords: "travel trip pack" },
      { char: "🗺️", name: "map", keywords: "travel directions explore" },
      { char: "📍", name: "pin", keywords: "location place map here" },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "🎉",
    emojis: [
      {
        char: "🎉",
        name: "party popper",
        keywords: "celebrate hooray congrats",
      },
      { char: "🎊", name: "confetti", keywords: "celebrate party" },
      { char: "🎈", name: "balloon", keywords: "party celebrate birthday" },
      { char: "🎁", name: "gift", keywords: "present birthday surprise" },
      { char: "🎀", name: "ribbon", keywords: "bow gift pretty" },
      { char: "🎵", name: "note", keywords: "music song sound" },
      { char: "🎶", name: "notes", keywords: "music song sound" },
      {
        char: "🎧",
        name: "headphones",
        keywords: "music listen audio podcast",
      },
      { char: "📚", name: "books", keywords: "read study learn" },
      { char: "📖", name: "open book", keywords: "read study story" },
      { char: "✏️", name: "pencil", keywords: "write edit note" },
      { char: "📝", name: "memo", keywords: "note write list" },
      { char: "📅", name: "calendar", keywords: "date schedule event" },
      { char: "📆", name: "tear calendar", keywords: "date schedule" },
      { char: "⏰", name: "alarm clock", keywords: "time reminder morning" },
      { char: "🔔", name: "bell", keywords: "notify reminder alert" },
      { char: "📣", name: "megaphone", keywords: "announce shout news" },
      { char: "📢", name: "loudspeaker", keywords: "announce news alert" },
      { char: "💡", name: "bulb", keywords: "idea tip bright" },
      { char: "🔑", name: "key", keywords: "unlock access secret" },
      { char: "🎨", name: "palette", keywords: "art paint creative" },
      { char: "🧵", name: "thread", keywords: "sew craft" },
      { char: "🕯️", name: "candle", keywords: "light calm cozy relax" },
      { char: "🛍️", name: "shopping bags", keywords: "shop buy" },
      { char: "💌", name: "love letter", keywords: "note message heart mail" },
      { char: "📸", name: "camera flash", keywords: "photo picture" },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "❤️",
    emojis: [
      { char: "❤️", name: "red heart", keywords: "love like" },
      { char: "🧡", name: "orange heart", keywords: "love" },
      { char: "💛", name: "yellow heart", keywords: "love" },
      { char: "💚", name: "green heart", keywords: "love nature" },
      { char: "💙", name: "blue heart", keywords: "love" },
      { char: "💜", name: "purple heart", keywords: "love" },
      { char: "🖤", name: "black heart", keywords: "love" },
      { char: "🤍", name: "white heart", keywords: "love pure" },
      { char: "🤎", name: "brown heart", keywords: "love" },
      { char: "💗", name: "growing heart", keywords: "love" },
      { char: "💕", name: "two hearts", keywords: "love like" },
      { char: "💖", name: "sparkling heart", keywords: "love shine" },
      { char: "💞", name: "revolving hearts", keywords: "love" },
      { char: "💘", name: "heart arrow", keywords: "love cupid crush" },
      { char: "💝", name: "heart gift", keywords: "love present" },
      { char: "💯", name: "hundred", keywords: "perfect score keep it real" },
      { char: "✅", name: "check", keywords: "done yes correct complete" },
      { char: "☑️", name: "checkbox", keywords: "done checked" },
      { char: "✔️", name: "check mark", keywords: "done yes" },
      { char: "➕", name: "plus", keywords: "add more and" },
      { char: "❗", name: "exclamation", keywords: "important alert" },
      { char: "❓", name: "question", keywords: "ask help" },
      { char: "💬", name: "speech", keywords: "comment message chat" },
      { char: "♻️", name: "recycle", keywords: "eco green reuse" },
      { char: "〰️", name: "wavy dash", keywords: "line divider" },
      { char: "🔆", name: "bright", keywords: "shine sun light" },
    ],
  },
];
