name: CI Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-checks:
    name: Code Quality & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run ESLint
        run: npm run lint

      - name: Check TypeScript types
        run: npx tsc --noEmit

      - name: Run build
        run: npm run build
        env:
          # Skip telemetry during CI
          NEXT_TELEMETRY_DISABLED: 1

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Uncommitted changes detected:"
            git status --short
            echo ""
            echo "Please run the following commands locally and commit the changes:"
            echo "  npm run lint:fix"
            echo "  npx prisma generate"
            exit 1
          else
            echo "✅ No uncommitted changes detected"
          fi

  # Optional: Run tests if you have them
  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   needs: quality-checks
  #   
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'
  #
  #     - name: Install dependencies
  #       run: npm ci
  #
  #     - name: Run tests
  #       run: npm test 